services:
  postgres:
    image: postgres:16-alpine
    container_name: blaze-store-postgres-dev
    env_file:
      - .env.dev
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  mailpit:
    image: axllent/mailpit:latest
    container_name: blaze-store-mailpit-dev
    env_file:
      - .env.dev
    ports:
      - "${MAIL_WEB_PORT}:8025"
      - "${MAIL_PORT}:1025"

volumes:
  postgres_data:
